import type { Receta } from '@/types'

export function getRecetas(): Receta[] {
  return RECETAS
}

export function getRecetaBySlug(slug: string): Receta | undefined {
  return RECETAS.find((r) => r.slug === slug)
}

export const CATEGORIAS = ['Todas', 'Desayuno', 'Entreno', 'Snacks'] as const

export const RECETAS: Receta[] = [
  {
    slug: 'alfajores-mani-sin-azucar',
    titulo: 'Alfajores de maní sin azúcar',
    descripcion: 'Un clásico reinventado para vitrinas y cartas naturales.',
    tiempo: '30 min',
    porciones: '20 unidades',
    dificultad: 'Medio',
    categoria: 'Entreno',
    imagen: '/lifestyle/recetas/receta-alfajores-mani.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '200 g de Crema de Maní Natural HARDY',
      '150 g de harina de almendras',
      '80 g de Miel Líquida HARDY',
      '50 g de cacao amargo en polvo',
      '1 pizca de sal',
    ],
    preparacion: [
      'Mezclá la crema de maní, la harina de almendras y la miel hasta obtener una masa firme.',
      'Estirá entre dos papeles de horno hasta ~5 mm de espesor.',
      'Cortá círculos con cortante de 6 cm.',
      'Horneá a 170°C por 10-12 minutos. Dejá enfriar.',
      'Rellená con crema de maní. Rebozá los bordes con cacao.',
    ],
    notaB2B: {
      texto: '¿Hacés esto a escala? El balde de 4,5 kg te rinde ~22 tandas de esta receta.',
      cta: 'Consultá formato a granel →',
      href: '/a-granel',
    },
  },
  {
    slug: 'tostadas-crema-mani-banana',
    titulo: 'Tostadas con crema de maní y banana',
    descripcion: 'Desayuno simple, real y energético.',
    tiempo: '5 min',
    porciones: '1 porción',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-16.png',
    productos: ['Crema de Maní Natural 380g'],
    ingredientes: [
      '2 rodajas de pan integral',
      '2 cdas de Crema de Maní Natural HARDY',
      '1 banana en rodajas',
      'Canela a gusto',
    ],
    preparacion: [
      'Tostá el pan hasta que esté dorado.',
      'Untá cada tostada con una cucharada generosa de Crema de Maní Natural HARDY.',
      'Colocá las rodajas de banana encima.',
      'Espolvoreá con canela a gusto y servir.',
    ],
    macros: { kcal: 310, proteinas: 10, carbos: 38, grasas: 13 },
  },
  {
    slug: 'bowl-crunchy',
    titulo: 'Bowl con Crunchy',
    descripcion: 'Una opción práctica para pre o post entrenamiento.',
    tiempo: '5 min',
    porciones: '1 porción',
    dificultad: 'Fácil',
    categoria: 'Entreno',
    imagen: '/lifestyle/recetas/receta-15.png',
    productos: ['Crema de Maní Crunchy 380g'],
    ingredientes: [
      '1 taza de yogur natural',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '1 banana en rodajas',
      '3 cdas de granola',
      'Maní tostado a gusto',
    ],
    preparacion: [
      'Colocá el yogur en un bowl.',
      'Agregá la Crema de Maní Crunchy HARDY en el centro.',
      'Distribuí la banana y la granola alrededor.',
      'Terminá con maní tostado y servir frío.',
    ],
    macros: { kcal: 420, proteinas: 18, carbos: 32, grasas: 22 },
  },
  {
    slug: 'miel-cafe-tostadas',
    titulo: 'Miel, café y tostadas',
    descripcion: 'Una forma simple de sumar sabor real.',
    tiempo: '5 min',
    porciones: '1 porción',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-14.png',
    productos: ['Miel Líquida 500g'],
    ingredientes: [
      '2 rodajas de pan artesanal',
      '1 cda de Miel Líquida HARDY',
      '1 taza de café negro',
      'Manteca a gusto',
    ],
    preparacion: [
      'Tostá el pan hasta que esté crocante.',
      'Untá con manteca si lo preferís.',
      'Rociá con Miel Líquida HARDY en hilo fino.',
      'Acompañá con el café bien caliente.',
    ],
    macros: { kcal: 220, proteinas: 4, carbos: 42, grasas: 3 },
  },
  {
    slug: 'cookies-mani-miel',
    titulo: 'Cookies de maní y miel',
    descripcion: 'Sabor intenso, ingredientes reales y energía para todo el día.',
    tiempo: '15 min',
    porciones: '6-8 cookies',
    dificultad: 'Fácil',
    categoria: 'Snacks',
    imagen: '/lifestyle/recetas/receta-12.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '1 huevo',
      '3 cdas de avena',
      '2 cdas de Crema de Maní Natural HARDY',
      '1 cda de Miel Líquida HARDY',
      '1 puñado de chips de chocolate amargo',
    ],
    preparacion: [
      'Precalentá el horno a 180°C.',
      'Mezclá el huevo, la avena, la crema de maní y la miel.',
      'Agregá los chips y mezclá.',
      'Formá bolitas y aplastá sobre placa con papel manteca.',
      'Horneá 12-15 minutos hasta dorar.',
    ],
    macros: { kcal: 180, proteinas: 5, carbos: 22, grasas: 9 },
  },
  {
    slug: 'bites-banana',
    titulo: 'Bites de banana',
    descripcion: 'Un snack simple y potente. Sin azúcar agregada.',
    tiempo: '20 min',
    porciones: '8-10 bocados',
    dificultad: 'Fácil',
    categoria: 'Snacks',
    imagen: '/lifestyle/recetas/receta-11.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '2 bananas maduras',
      '2 cdas de Crema de Maní Natural HARDY',
      '1 cda de Miel Líquida HARDY',
      'Chocolate amargo derretido',
      'Maní picado para decorar',
    ],
    preparacion: [
      'Cortá las bananas en rodajas gruesas.',
      'Untá cada rodaja con Crema de Maní Natural HARDY.',
      'Rociá con Miel Líquida HARDY.',
      'Sumergí en chocolate y espolvoreá maní picado.',
      'Freezer 15 minutos y servir.',
    ],
    macros: { kcal: 140, proteinas: 3, carbos: 18, grasas: 7 },
  },
  {
    slug: 'pancakes-de-mani',
    titulo: 'Pancakes de maní',
    descripcion: 'Suaves, nutritivos y con un sabor que eleva tu rutina.',
    tiempo: '15 min',
    porciones: '6-8 pancakes',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-10.png',
    productos: ['Crema de Maní Crunchy 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '1 huevo',
      '1 banana madura',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '3 cdas de avena molida',
      'Miel Líquida HARDY para servir',
    ],
    preparacion: [
      'Pisá la banana y mezclá con el huevo, la crema y la avena.',
      'Cociná porciones en sartén caliente 2-3 min de cada lado.',
      'Servir con Miel Líquida HARDY y banana extra.',
    ],
    macros: { kcal: 380, proteinas: 14, carbos: 42, grasas: 16 },
  },
  {
    slug: 'energy-bites',
    titulo: 'Energy Bites',
    descripcion: 'Bocados nutritivos y simples. Sin azúcar agregada.',
    tiempo: '25 min',
    porciones: '12-15 bolitas',
    dificultad: 'Fácil',
    categoria: 'Snacks',
    imagen: '/lifestyle/recetas/receta-09.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Sólida 500g'],
    ingredientes: [
      '1 taza de avena',
      '3 cdas de Crema de Maní Natural HARDY',
      '2 cdas de Miel Sólida HARDY',
      '2 cdas de chips de chocolate',
      'Coco rallado para cubrir',
    ],
    preparacion: [
      'Mezclá avena, crema de maní y miel.',
      'Agregá chips y mezclá.',
      'Formá bolitas con manos húmedas.',
      'Pasá por coco rallado.',
      'Refrigerá 20 minutos antes de servir.',
    ],
    macros: { kcal: 120, proteinas: 4, carbos: 12, grasas: 7 },
  },
  {
    slug: 'granola-casera',
    titulo: 'Granola casera',
    descripcion: 'Crujiente, dulce y natural. Energía sostenida para todo el día.',
    tiempo: '25 min',
    porciones: '1 frasco grande',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-07.png',
    productos: ['Crema de Maní Crunchy 380g', 'Miel Sólida 500g'],
    ingredientes: [
      '2 tazas de avena',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '3 cdas de Miel Sólida HARDY',
      '1 puñado de frutos secos mixtos',
      'Semillas de chía a gusto',
    ],
    preparacion: [
      'Precalentá el horno a 160°C.',
      'Derretí la miel y mezclá con la crema de maní.',
      'Integrá avena, frutos secos y semillas.',
      'Extendé en placa y horneá 20 min revolviendo a mitad.',
      'Enfriar completamente antes de guardar.',
    ],
    macros: { kcal: 280, proteinas: 7, carbos: 35, grasas: 13 },
  },
  {
    slug: 'barritas-energeticas',
    titulo: 'Barritas energéticas',
    descripcion: 'Crocantes, nutritivas y sin aditivos.',
    tiempo: '45 min',
    porciones: '8-10 barritas',
    dificultad: 'Fácil',
    categoria: 'Snacks',
    imagen: '/lifestyle/recetas/receta-06.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Sólida 500g'],
    ingredientes: [
      '2 tazas de avena',
      '4 cdas de Crema de Maní Natural HARDY',
      '3 cdas de Miel Sólida HARDY',
      '1 puñado de chips de chocolate',
      '2 cdas de semillas mixtas',
    ],
    preparacion: [
      'Precalentá el horno a 170°C.',
      'Derretí la miel y mezclá con la crema de maní.',
      'Integrá avena, chocolate y semillas.',
      'Volcá en molde cuadrado forrado.',
      'Horneá 20-25 minutos hasta dorar.',
      'Enfriar y cortar en barritas.',
    ],
    macros: { kcal: 190, proteinas: 6, carbos: 24, grasas: 9 },
  },
  {
    slug: 'smoothie-proteico',
    titulo: 'Smoothie proteico',
    descripcion: 'Cremoso, nutritivo y listo en 5 minutos.',
    tiempo: '5 min',
    porciones: '1 vaso grande',
    dificultad: 'Fácil',
    categoria: 'Entreno',
    imagen: '/lifestyle/recetas/receta-05.png',
    productos: ['Crema de Maní Crunchy 380g'],
    ingredientes: [
      '1 banana congelada',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '1 taza de leche o vegetal',
      '1 cda de cacao puro',
      'Hielo a gusto',
    ],
    preparacion: [
      'Colocá todos los ingredientes en la licuadora.',
      'Licuá hasta obtener textura cremosa.',
      'Servir en vaso alto con hielo.',
      'Decorar con maní tostado opcional.',
    ],
    macros: { kcal: 390, proteinas: 20, carbos: 38, grasas: 16 },
  },
  {
    slug: 'parfait-mani',
    titulo: 'Parfait de maní',
    descripcion: 'Fresco y equilibrado. Para arrancar bien.',
    tiempo: '10 min',
    porciones: '1 frasco',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-04.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '1 taza de yogur griego',
      '2 cdas de Crema de Maní Natural HARDY',
      '1 cda de Miel Líquida HARDY',
      '1 banana en rodajas',
      '2 cdas de granola',
    ],
    preparacion: [
      'En un frasco, colocá una capa de yogur.',
      'Agregá la crema de maní en hilo.',
      'Sumá banana y granola.',
      'Repetí las capas.',
      'Terminá con Miel Líquida HARDY.',
    ],
    macros: { kcal: 350, proteinas: 14, carbos: 40, grasas: 14 },
  },
  {
    slug: 'porridge-mani',
    titulo: 'Porridge de maní',
    descripcion: 'Cremoso y nutritivo para arrancar el día con energía.',
    tiempo: '10 min',
    porciones: '1 porción',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-03.png',
    productos: ['Crema de Maní Crunchy 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '½ taza de avena',
      '1 taza de leche',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '1 cda de Miel Líquida HARDY',
      'Frutos rojos para decorar',
    ],
    preparacion: [
      'Cociná la avena con la leche a fuego medio 5 minutos.',
      'Agregá la crema de maní y revolvé.',
      'Volcá en bowl.',
      'Decorá con frutos rojos y rociá con Miel Líquida HARDY.',
    ],
    macros: { kcal: 420, proteinas: 16, carbos: 52, grasas: 15 },
  },
  {
    slug: 'waffles-mani',
    titulo: 'Waffles de maní',
    descripcion: 'Livianos y nutritivos. Sin azúcar ni aceite.',
    tiempo: '20 min',
    porciones: '2 porciones',
    dificultad: 'Medio',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-02.png',
    productos: ['Crema de Maní Natural 380g', 'Miel Sólida 500g'],
    ingredientes: [
      '1 taza de harina integral',
      '1 huevo',
      '1 taza de leche',
      '2 cdas de Crema de Maní Natural HARDY',
      'Miel Sólida HARDY para servir',
      'Banana y frutos rojos',
    ],
    preparacion: [
      'Mezclá harina, huevo, leche y crema de maní.',
      'Cociná en wafflera hasta dorar.',
      'Servir con Miel Sólida HARDY, banana y frutos rojos.',
    ],
    macros: { kcal: 460, proteinas: 16, carbos: 55, grasas: 18 },
  },
  {
    slug: 'yogurt-bowl',
    titulo: 'Yogurt bowl',
    descripcion: 'Fresco y equilibrado. Listo en 5 minutos.',
    tiempo: '5 min',
    porciones: '1 porción',
    dificultad: 'Fácil',
    categoria: 'Desayuno',
    imagen: '/lifestyle/recetas/receta-01.png',
    productos: ['Crema de Maní Crunchy 380g', 'Miel Líquida 500g'],
    ingredientes: [
      '1 taza de yogur natural',
      '2 cdas de Crema de Maní Crunchy HARDY',
      '1 cda de Miel Líquida HARDY',
      'Granola, fresas y kiwi para decorar',
    ],
    preparacion: [
      'Colocá el yogur en un bowl amplio.',
      'Agregá la crema de maní en el centro.',
      'Decorá con fruta y granola.',
      'Rociá con Miel Líquida HARDY y servir.',
    ],
    macros: { kcal: 340, proteinas: 18, carbos: 36, grasas: 14 },
  },
]
